---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: IMAGE_PLACEHOLDER
          ports:
            - name: http-metrics  # Named port (important for ServiceMonitor)
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http-metrics  # Named port (important for ServiceMonitor)
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: prometheus  # Ensure this is where Prometheus is running
  labels:
    release: prometheus  # Match your Prometheus Operator installation
spec:
  selector:
    matchLabels:
      app: flask-app  # This should match the Service label
  namespaceSelector:
    matchNames:
      - default  # Ensure this matches the namespace of your Flask app
  endpoints:
    - port: http-metrics  # Must match the port name in the Service
      path: /metrics
      interval: 15s