name: My First GitHub Actions
on: [push]

jobs:
  build:
    runs-on: macOS

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      run: |
        ls -ltrh
        docker build -t ravitripathi/api:v1 .
        docker push ravitripathi/api:v1
    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f api.yaml