name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: macOS

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ravitripathi/api:v1

    - name: Build and Push Docker Image
      run: |
        ls -ltrh
        docker build -t ravitripathi/api:v1 .
        docker push ravitripathi/api:v1
        
    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f api.yaml