name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: macOS

    steps:
    - name: Build Docker Image
      run: |
        ls -ltrh
        docker build -t ecs-api:latest .
        minikube image load ecs-api:latest
    - name: Update Kubernetes Deployment YAML
      run: |
        sed -i 's|IMAGE_PLACEHOLDER|ecs-api:latest|g' k8s/deployment.yaml
    - name: Apply Kubernetes Manifest
      run: |
        kubectl apply -f api.yaml